services:
  - type: web
    name: song-api
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: song-api-db
          property: internalConnectionString
      - key: DB_HOST
        fromDatabase:
          name: song-api-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: song-api-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: song-api-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: song-api-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: song-api-db
          property: password
      - key: DB_PARAMS
        value: ?sslmode=require
      - key: ALLOWED_ORIGINS
        value: http://localhost:5173,https://song-ui-hfg8.onrender.com
