services:
  - type: web
    name: song-api
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      # Supabase requires SSL. This suffix is appended to the JDBC URL constructed in application.properties.
      # Example: ?sslmode=require
      - key: DB_PARAMS
        value: ?sslmode=require
